# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    working_directory: /go/src/github.com/matsu0228/gotest
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -u github.com/golang/dep/cmd/dep
      ##  debug --------------------------------
      # - run: pwd
      # - run: echo $GOPATH
      # - run: dep ensure -v

      ## test  ----------------------------------
      - run: go test -v github.com/matsu0228/gotest/tips
      - run: go test -v github.com/matsu0228/gotest/integrate
      - run: go test -v github.com/matsu0228/gotest/integrate/repository
      - run: go test -v -tags=integrate github.com/matsu0228/gotest/integrate/repogitory
      # - run: go test -v -race ./...
      
      ## metalinter -----------------------------
      - run: go get golang.org/x/lint/golint
      - run: go get github.com/haya14busa/goverage
      - run: golint ./...
      - run: go vet ./...