version: '2'
services:
  db:
    build: ./db/
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      # MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
  # app:
  #   build: ./app/
  #   ports:
  #     - "8080:80"
  #   links:
  #     - db
  #   volumes:
  #     - ./src:/var/www/html
  #   stdin_open: true
  #   tty: true